In [134]:
import numpy as np
import operator

In [87]:
#读取数据
f=open("./Iris_Data_Set.txt")
arraylines = f.readlines()#逐行读取数据，存储在一个list中
numberoflines = len(arraylines)


In [97]:
#数据初始化
trainingData = np.zeros([int(numberoflines/5)*4,4])#新建矩阵，存储4个属性值
validatingData=np.zeros([int(numberoflines/5),4])
trainingClass = []#类型：numpy.ndarray-n维数组
validatingClass=[]
print(trainingData)
print(trainingClass)
print(validatingData)
print(validatingClass)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0

In [98]:
trainingIndex = 0
validatingIndex=0
flag=0
for line in arraylines:
    line=line.strip('\n')#去除行末的换行符
    listFromLine = line.split(',')#type:list
    if flag%5!=0:#训练数据
        print(trainingIndex)
        trainingData[trainingIndex,:] = listFromLine[0:4]#第1到4个
        if listFromLine[-1]=="Iris-setosa":
            trainingClass.append(1)
        elif listFromLine[-1]=="Iris-versicolor":
            trainingClass.append(2)
        else:
            trainingClass.append(3)
        trainingIndex+=1
    else:
        print(validatingIndex)
        validatingData[validatingIndex,:]=listFromLine[0:4]
        if listFromLine[-1]=="Iris-setosa":
            validatingClass.append(1)
        elif listFromLine[-1]=="Iris-versicolor":
            validatingClass.append(2)
        else:
            validatingClass.append(3)
        validatingIndex+=1
    flag+=1

0
0
1
2
3
1
4
5
6
7
2
8
9
10
11
3
12
13
14
15
4
16
17
18
19
5
20
21
22
23
6
24
25
26
27
7
28
29
30
31
8
32
33
34
35
9
36
37
38
39
10
40
41
42
43
11
44
45
46
47
12
48
49
50
51
13
52
53
54
55
14
56
57
58
59
15
60
61
62
63
16
64
65
66
67
17
68
69
70
71
18
72
73
74
75
19
76
77
78
79
20
80
81
82
83
21
84
85
86
87
22
88
89
90
91
23
92
93
94
95
24
96
97
98
99
25
100
101
102
103
26
104
105
106
107
27
108
109
110
111
28
112
113
114
115
29
116
117
118
119


In [99]:
print(trainingData)
print(trainingClass)
print(validatingData)
print(validatingClass)

[[ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5  1.6  0.6]
 [ 5.1  3.8  1.9  0.4]
 [ 5.1  3.8  1.6  0.2]
 [ 4.6  3.2  1.4  0.2]
 [ 5.3  3.7  1.5  0.2]
 [ 5.   3.3  1.4  0.2]
 [ 6.4  3.2  4.5  1.5]
 [ 6.9  3.1  4.9  1.5]
 [ 5.5  2.3  4.   1.3]
 [ 6.5  2.8

In [186]:
#选择合适的k值
k=4
correct=0
validatingIndex=0
for v in validatingData:
    dist=[]
    index=0
    for t in trainingData:
        distance=pow(((v-t)*(v-t)).sum(),0.5)#欧式距离
        dist.append([index,distance])
        index+=1
    dist.sort(key=lambda dist: dist[1]) #根据dist排序
    #选择dist最小k个
    dist=dist[0:k]
    #print(dist)
    classes=[0,0,0]
    for i in dist:
        #print(i[0])
        if trainingClass[i[0]]==1:
            classes[0]+=1
        elif trainingClass[i[0]]==2:
            classes[1]+=1
        else:
            classes[2]+=1
    #print(classes)
    #返回最可能的类别的索引
    predicted_value=classes.index(max(classes))+1
    actual_value=validatingClass[validatingIndex]
    if predicted_value==actual_value:
        correct+=1
    #else:
        #print(validatingIndex)
        #print(predicted_value)
        #print(actual_value)
    validatingIndex+=1
print("correct_rate=%f"%(correct/30))

correct_rate=0.966667


In [187]:
from sklearn.neighbors import KNeighborsClassifier  

In [190]:
X = [[0], [1], [2], [3]]
y = [0, 0, 1, 1]
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X, y) 

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [191]:
print(neigh.predict([[1.1]]))

[0]


In [192]:
print(neigh.predict_proba([[0.9]]))

[[ 0.66666667  0.33333333]]
